-- MoneyFlow financial feature tables.
-- RLS is enabled separately in Supabase; the Render API uses the private database connection.

create table if not exists public.budgets (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  category varchar(80) not null,
  monthly_limit numeric(14, 2) not null check (monthly_limit > 0),
  created_at timestamptz not null default now()
);

create index if not exists budgets_user_id_idx on public.budgets(user_id);
alter table public.budgets enable row level security;

create table if not exists public.loans (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  name varchar(160) not null,
  remaining_balance numeric(14, 2) not null check (remaining_balance >= 0),
  minimum_payment numeric(14, 2) not null default 0 check (minimum_payment >= 0),
  interest_rate numeric(6, 3) not null default 0 check (interest_rate >= 0),
  due_date date,
  created_at timestamptz not null default now()
);

create index if not exists loans_user_id_idx on public.loans(user_id);
alter table public.loans enable row level security;

create table if not exists public.goals (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  name varchar(160) not null,
  target_amount numeric(14, 2) not null check (target_amount > 0),
  current_amount numeric(14, 2) not null default 0 check (current_amount >= 0),
  target_date date,
  created_at timestamptz not null default now()
);

create index if not exists goals_user_id_idx on public.goals(user_id);
alter table public.goals enable row level security;
