create table if not exists public.loan_payments (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  loan_id integer not null references public.loans(id) on delete cascade,
  amount numeric(14, 2) not null check (amount > 0),
  principal_amount numeric(14, 2) not null check (principal_amount > 0),
  interest_amount numeric(14, 2) not null default 0 check (interest_amount >= 0),
  paid_on date not null default current_date,
  note text,
  created_at timestamptz not null default now(),
  constraint loan_payment_parts_match check (principal_amount + interest_amount = amount)
);

create index if not exists loan_payments_user_id_idx on public.loan_payments(user_id);
create index if not exists loan_payments_loan_id_idx on public.loan_payments(loan_id);
alter table public.loan_payments enable row level security;
