create table if not exists public.recurring_bills (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  name varchar(160) not null,
  amount numeric(14, 2) not null check (amount > 0),
  category varchar(80) not null default 'Other',
  frequency varchar(20) not null check (frequency in ('weekly', 'monthly', 'yearly')),
  next_due date not null,
  is_archived boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists recurring_bills_user_due_idx on public.recurring_bills(user_id, next_due);
alter table public.recurring_bills enable row level security;
