import { useState } from "react";
import { currency } from "./format";
import { Account } from "./types";

function AccountForm({ account, onSubmit, onCancel }: { account?: Account; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void; onCancel?: () => void }) {
  return <form className="inline-form feature-form" onSubmit={onSubmit}>{account ? <h2>Edit account</h2> : <><h2>Add an account</h2><p>Create a checking, savings, cash, or credit account.</p></>} {account && <input type="hidden" name="account_id" value={account.id} />}<label>Name<input name="name" defaultValue={account?.name} placeholder="e.g. Credit card" required /></label><label>Type<select name="type" defaultValue={account?.type || "Checking"}><option>Checking</option><option>Savings</option><option>Cash</option><option>Credit card</option><option>Investment</option></select></label><label>Opening balance<input name="balance" type="number" step="0.01" defaultValue={account?.openingBalance ?? 0} required /></label><button className="primary-button full" type="submit">{account ? "Save changes" : "Save account"}</button>{onCancel && <button className="text-button" type="button" onClick={onCancel}>Cancel</button>}</form>;
}

export function Accounts({ accounts, onSubmit, onRemove }: { accounts: Account[]; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void; onRemove: (id: string) => void }) {
  const [editingId, setEditingId] = useState<string | null>(null);
  return <div className="feature-grid"><section className="panel"><div className="panel-heading"><div><h2>Your accounts</h2><p>Balances across your money</p></div></div>{accounts.length ? accounts.map(account => editingId === account.id ? <AccountForm account={account} key={account.id} onSubmit={event => { event.preventDefault(); onSubmit(event); setEditingId(null); }} onCancel={() => setEditingId(null)} /> : <div className="account-row" key={account.id}><div className="account-icon">▣</div><div><strong>{account.name}</strong><small>{account.type} · {account.currency}</small></div><b>{currency(account.balance)}</b><button type="button" className="edit-link" onClick={() => setEditingId(account.id)} aria-label={`Edit ${account.name} account`}>✎</button><button type="button" className="delete-link" onClick={() => { if (window.confirm(`Archive ${account.name}? Transactions will be preserved.`)) void onRemove(account.id); }} aria-label={`Remove ${account.name} account`}>×</button></div>) : <div className="empty-state">No accounts yet. Add your first one.</div>}</section><AccountForm onSubmit={onSubmit} /></div>;
}
