import { useEffect, useState } from "react";
import { localDateString } from "../../services/localDate";
import { CalendarInput } from "./CalendarInput";
import { Account, Transaction } from "./types";

export function AddTransactionModal({ accounts, onClose, onSubmit, initialTransaction }: { accounts: Account[]; onClose: () => void; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void; initialTransaction?: Transaction }) {
  const [type, setType] = useState<"expense" | "income">(initialTransaction?.type || "expense");
  useEffect(() => { const previousOverflow = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = previousOverflow; }; }, []);
  const expenseCategories = ["Housing", "Food & groceries", "Dining out", "Transportation", "Shopping", "Subscriptions", "Utilities", "Healthcare", "Education", "Personal care", "Gifts & donations", "Entertainment", "Other"];
  const incomeCategories = ["Salary", "Freelance", "Business income", "Interest", "Dividends", "Refund", "Gift", "Government benefit", "Other income"];
  const [category, setCategory] = useState(initialTransaction?.category || expenseCategories[1]);
  const isIncome = type === "income";
  const changeType = (nextType: "expense" | "income") => { setType(nextType); setCategory(nextType === "income" ? incomeCategories[0] : expenseCategories[1]); };
  const categories = isIncome ? incomeCategories : expenseCategories;
  return <div className="modal-backdrop" onClick={onClose}><form className="modal" onSubmit={onSubmit} onClick={event => event.stopPropagation()}><div className="modal-heading"><div><p className="eyebrow">{initialTransaction ? "EDIT ENTRY" : isIncome ? "INCOME ENTRY" : "EXPENSE ENTRY"}</p><h2>{initialTransaction ? "Edit transaction" : isIncome ? "Add income" : "Add expense"}</h2><p className="form-hint">{isIncome ? "Record money received and where it came from." : "Record where your money went."}</p></div><button type="button" className="close-button" onClick={onClose}>×</button></div><label>Entry type<select name="type" value={type} onChange={event => changeType(event.target.value as "expense" | "income")}><option value="expense">Expense</option><option value="income">Income</option></select></label>{isIncome ? <label>Income source<input name="name" defaultValue={initialTransaction?.name} placeholder="e.g. Employer paycheck" required /></label> : <label>Merchant or description<input name="name" defaultValue={initialTransaction?.name} placeholder="e.g. Grocery store" required /></label>}<label>{isIncome ? "Amount received" : "Amount spent"}<input name="amount" type="number" min="0.01" step="0.01" defaultValue={initialTransaction?.amount} placeholder="0.00" required /></label><label>{isIncome ? "Income type" : "Expense category"}<select name="category" value={category} onChange={event => setCategory(event.target.value)}>{categories.map(item => <option key={item}>{item}</option>)}</select></label><label>{isIncome ? "Received into" : "Paid from"}<select name="account" defaultValue={initialTransaction?.account || accounts[0]?.name} required>{accounts.map(account => <option key={account.id}>{account.name}</option>)}</select></label><label>{isIncome ? "Received date" : "Purchase date"}<CalendarInput name="occurred_on" defaultValue={initialTransaction?.date || localDateString()} required /></label><label>Notes<input name="notes" defaultValue={initialTransaction?.notes} placeholder={isIncome ? "Optional note, pay period, or source details" : "Optional note, receipt, or context"} /></label><button className="primary-button full" type="submit">{initialTransaction ? "Save changes" : isIncome ? "Save income" : "Save expense"}</button></form></div>;
}
