import { useState } from "react";
import { Account } from "./types";

export function AddTransactionModal({ accounts, onClose, onSubmit }: { accounts: Account[]; onClose: () => void; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void }) {
  const [type, setType] = useState<"expense" | "income">("expense");
  const expenseCategories = ["Housing", "Food & groceries", "Dining out", "Transportation", "Shopping", "Subscriptions", "Utilities", "Healthcare", "Education", "Personal care", "Gifts & donations", "Entertainment", "Other"];
  const incomeCategories = ["Salary", "Freelance", "Business income", "Interest", "Dividends", "Refund", "Gift", "Government benefit", "Other income"];
  const isIncome = type === "income";
  return <div className="modal-backdrop" onClick={onClose}><form className="modal" onSubmit={onSubmit} onClick={event => event.stopPropagation()}><div className="modal-heading"><div><p className="eyebrow">{isIncome ? "INCOME ENTRY" : "EXPENSE ENTRY"}</p><h2>{isIncome ? "Add income" : "Add expense"}</h2><p className="form-hint">{isIncome ? "Record money received and where it came from." : "Record where your money went."}</p></div><button type="button" className="close-button" onClick={onClose}>×</button></div><label>Entry type<select name="type" value={type} onChange={event => setType(event.target.value as "expense" | "income")}><option value="expense">Expense</option><option value="income">Income</option></select></label>{isIncome ? <label>Income source<input name="name" placeholder="e.g. Employer paycheck" required /></label> : <label>Merchant or description<input name="name" placeholder="e.g. Grocery store" required /></label>}<label>{isIncome ? "Amount received" : "Amount spent"}<input name="amount" type="number" min="0.01" step="0.01" placeholder="0.00" required /></label><label>{isIncome ? "Income type" : "Expense category"}<select name="category" defaultValue={isIncome ? "Salary" : "Food & groceries"}>{(isIncome ? incomeCategories : expenseCategories).map(category => <option key={category}>{category}</option>)}</select></label><label>{isIncome ? "Received into" : "Paid from"}<select name="account" defaultValue={accounts[0]?.name} required>{accounts.map(account => <option key={account.id}>{account.name}</option>)}</select></label><label>{isIncome ? "Received date" : "Purchase date"}<input name="occurred_on" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><label>Notes<input name="notes" placeholder={isIncome ? "Optional note, pay period, or source details" : "Optional note, receipt, or context"} /></label><button className="primary-button full" type="submit">{isIncome ? "Save income" : "Save expense"}</button></form></div>;
}
