import { FormEvent, useEffect, useState } from "react";

export function AuthScreen({ error, loading, onLogin, onRegister }: { error: string; loading: boolean; onLogin: (email: string, password: string) => void; onRegister: (email: string, password: string, displayName: string) => void }) {
  const [registering, setRegistering] = useState(false);
  const [email, setEmail] = useState("");
  const [rememberEmail, setRememberEmail] = useState(true);
  useEffect(() => { const savedEmail = window.localStorage.getItem("moneyflow_login_email"); if (savedEmail) setEmail(savedEmail); }, []);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const submittedEmail = String(data.get("email")); const password = String(data.get("password")); if (!registering) { if (rememberEmail) window.localStorage.setItem("moneyflow_login_email", submittedEmail); else window.localStorage.removeItem("moneyflow_login_email"); onLogin(submittedEmail, password); } else onRegister(submittedEmail, password, String(data.get("displayName"))); };
  return <main className="auth-shell"><section className="auth-card"><div className="brand auth-brand"><span className="brand-mark">✦</span><span>Money<span className="brand-accent">Flow</span></span></div><p className="eyebrow">PRIVATE FINANCE WORKSPACE</p><h1>{registering ? "Create your account" : "Welcome back"}</h1><p className="auth-subtitle">{registering ? "Start organizing your money in one secure place." : "Sign in to continue to your finances."}</p><form onSubmit={submit} autoComplete={registering ? "on" : "on"}>{registering && <label>Name<input name="displayName" autoComplete="name" placeholder="Your name" required /></label>}<label>Email<input name="email" type="email" value={email} onChange={event => setEmail(event.target.value)} autoComplete="username" placeholder="you@example.com" required /></label><label>Password<input name="password" type="password" minLength={12} autoComplete={registering ? "new-password" : "current-password"} placeholder="At least 12 characters" required /></label>{!registering && <label className="remember-row"><input type="checkbox" checked={rememberEmail} onChange={event => setRememberEmail(event.target.checked)} />Remember email on this device</label>}{error && <p className="auth-error" role="alert">{error}</p>}<button className="primary-button full" disabled={loading}>{loading ? "Please wait…" : registering ? "Create account" : "Sign in"}</button></form><button type="button" className="auth-switch" onClick={() => setRegistering(value => !value)}>{registering ? "Already have an account? Sign in" : "Need an account? Create one"}</button><small className="auth-note">Your browser can save the password securely. MoneyFlow never stores raw passwords.</small></section></main>;
}
