import { FormEvent, useState } from "react";
import { ApiBudget, ApiGoal, ApiLoan, ApiLoanPayment } from "../../services/api";
import { CalendarInput } from "./CalendarInput";
import { currency } from "./format";
import { Tab } from "./types";

type FeatureProps = { tab: Tab; budgets: ApiBudget[]; loans: ApiLoan[]; goals: ApiGoal[]; loanPayments: Record<number, ApiLoanPayment[]>; onAddBudget: (event: FormEvent<HTMLFormElement>) => void | Promise<void>; onAddLoan: (event: FormEvent<HTMLFormElement>) => void | Promise<void>; onAddGoal: (event: FormEvent<HTMLFormElement>) => void | Promise<void>; onAddLoanPayment: (loanId: string, event: FormEvent<HTMLFormElement>) => void | Promise<void>; onRemoveBudget: (id: string) => void | Promise<void>; onRemoveLoan: (id: string) => void | Promise<void>; onRemoveGoal: (id: string) => void | Promise<void>; onRemoveLoanPayment: (loanId: string, paymentId: string) => void | Promise<void>; onNotice: (message: string) => void };

export function Feature({ tab, budgets, loans, goals, loanPayments, onAddBudget, onAddLoan, onAddGoal, onAddLoanPayment, onRemoveBudget, onRemoveLoan, onRemoveGoal, onRemoveLoanPayment, onNotice }: FeatureProps) {
  const [showForm, setShowForm] = useState(false);
  const [paymentLoanId, setPaymentLoanId] = useState<number | null>(null);
  const selected = { Budgets: { title: "Monthly budgets", text: "Set limits and understand category spending." }, Loans: { title: "Loan center", text: "Track principal, interest, due dates, and payoff progress." }, Goals: { title: "Financial goals", text: "Turn your plans into visible progress." } }[tab as "Budgets" | "Loans" | "Goals"];
  if (!selected) return null;
  const records = tab === "Budgets" ? budgets : tab === "Loans" ? loans : goals;
  const submit = async (event: FormEvent<HTMLFormElement>) => { try { if (tab === "Budgets") await onAddBudget(event); else if (tab === "Loans") await onAddLoan(event); else await onAddGoal(event); setShowForm(false); onNotice(`${tab.slice(0, -1)} saved successfully.`); } catch (cause) { onNotice(cause instanceof Error ? cause.message : `Could not save ${tab.slice(0, -1).toLowerCase()}.`); } };
  const submitPayment = async (loanId: number, event: FormEvent<HTMLFormElement>) => { try { await onAddLoanPayment(String(loanId), event); setPaymentLoanId(null); onNotice("Loan payment saved successfully."); } catch (cause) { onNotice(cause instanceof Error ? cause.message : "Could not save loan payment."); } };
  return <div className="feature-grid"><section className="panel empty-feature"><div className="feature-symbol">{tab === "Loans" ? "▤" : tab === "Goals" ? "◎" : "◒"}</div><h2>{selected.title}</h2><p>{selected.text}</p><div className="record-list">
    {tab === "Budgets" && budgets.map(item => <div className="feature-placeholder feature-record" key={item.id}><span>{item.category} · {currency(item.monthly_limit)} monthly</span><button type="button" className="delete-link" onClick={() => { void onRemoveBudget(String(item.id)); }} aria-label={`Remove ${item.category} budget`}>×</button></div>)}
    {tab === "Loans" && loans.map(item => <div className="loan-record" key={item.id}><div className="feature-placeholder feature-record"><span>{item.name} · {currency(item.remaining_balance)} remaining</span><button type="button" className="delete-link" onClick={() => { void onRemoveLoan(String(item.id)); }} aria-label={`Remove ${item.name} loan`}>×</button></div><button type="button" className="text-button payment-button" onClick={() => setPaymentLoanId(paymentLoanId === item.id ? null : item.id)}>＋ Record payment</button>{loanPayments[item.id]?.map(payment => <div className="payment-row" key={payment.id}><span>{payment.paid_on} · {currency(payment.amount)} <small>(principal {currency(payment.principal_amount)} · interest {currency(payment.interest_amount)})</small></span><button type="button" className="delete-link" onClick={() => { void onRemoveLoanPayment(String(item.id), String(payment.id)); }} aria-label="Remove loan payment">×</button></div>)}{paymentLoanId === item.id && <form className="inline-form feature-form payment-form" onSubmit={event => { void submitPayment(item.id, event); }}><label>Payment amount<input name="amount" type="number" min="0.01" step="0.01" required /></label><label>Principal amount<input name="principal_amount" type="number" min="0.01" step="0.01" required /></label><label>Interest amount<input name="interest_amount" type="number" min="0" step="0.01" defaultValue="0" /></label><label>Paid on<CalendarInput name="paid_on" required /></label><button className="primary-button full" type="submit">Save payment</button></form>}</div>)}
    {tab === "Goals" && goals.map(item => <div className="feature-placeholder feature-record" key={item.id}><span>{item.name} · {currency(item.current_amount)} of {currency(item.target_amount)}</span><button type="button" className="delete-link" onClick={() => { void onRemoveGoal(String(item.id)); }} aria-label={`Remove ${item.name} goal`}>×</button></div>)}
    {!records.length && <div className="empty-state">No {tab.toLowerCase()} yet. Add your first one.</div>}
  </div>{showForm ? <form className="inline-form feature-form" onSubmit={event => { void submit(event); }}>
    {tab === "Budgets" && <><label>Category<input name="category" required /></label><label>Monthly limit<input name="monthly_limit" type="number" min="0.01" step="0.01" required /></label></>}
    {tab === "Loans" && <><label>Loan name<input name="name" required /></label><label>Remaining balance<input name="remaining_balance" type="number" min="0" step="0.01" required /></label><label>Minimum payment<input name="minimum_payment" type="number" min="0" step="0.01" defaultValue="0" /></label><label>Interest rate (%)<input name="interest_rate" type="number" min="0" step="0.001" defaultValue="0" /></label><label>Next due date<CalendarInput name="due_date" /></label></>}
    {tab === "Goals" && <><label>Goal name<input name="name" required /></label><label>Target amount<input name="target_amount" type="number" min="0.01" step="0.01" required /></label><label>Current amount<input name="current_amount" type="number" min="0" step="0.01" defaultValue="0" /></label><label>Target date<CalendarInput name="target_date" /></label></>}
    <button className="primary-button full" type="submit">Save {tab.slice(0, -1).toLowerCase()}</button>
  </form> : <button type="button" className="primary-button" onClick={() => setShowForm(true)}>＋ Add {tab.slice(0, -1).toLowerCase()}</button>}</section><section className="panel checklist"><h2>What you can manage here</h2>{["Add and remove records", "See progress over time", "Keep everything in one view"].map(item => <div key={item}>✓ <span>{item}</span></div>)}</section></div>;
}
