import { useMemo } from "react";
import { currency } from "./format";
import { Legend } from "./Legend";
import { Transactions } from "./Transactions";
import { Upcoming } from "./Upcoming";
import { Transaction } from "./types";

export function Overview({ transactions, balance, onViewTransactions }: { transactions: Transaction[]; balance: number; onViewTransactions: () => void }) {
  const totals = useMemo(() => ({ income: transactions.filter(t => t.type === "income").reduce((sum, t) => sum + t.amount, 0), spending: transactions.filter(t => t.type === "expense").reduce((sum, t) => sum + t.amount, 0) }), [transactions]);
  const rate = totals.income ? Math.max(0, Math.round((1 - totals.spending / totals.income) * 100)) : 0;
  return <><div className="stats-grid"><article className="stat-card balance-card"><div className="stat-label">TOTAL BALANCE <span className="help">?</span></div><div className="stat-value">{currency(balance)}</div><div className="stat-foot positive">↗ 12.8% <span>vs last month</span></div><div className="sparkline"><span /><span /><span /><span /><span /><span /><span /><span /><span /><span /></div></article><article className="stat-card"><div className="stat-label">INCOME <span className="period">THIS MONTH⌄</span></div><div className="stat-value">{currency(totals.income)}</div><div className="stat-foot positive">↗ Updated live <span>from transactions</span></div></article><article className="stat-card"><div className="stat-label">SPENDING <span className="period">THIS MONTH⌄</span></div><div className="stat-value">{currency(totals.spending)}</div><div className="stat-foot negative">↘ Tracked live <span>from transactions</span></div></article><article className="stat-card"><div className="stat-label">SAVINGS RATE <span className="help">?</span></div><div className="stat-value">{rate}<span className="cents">%</span></div><div className="progress"><span style={{ width: `${rate}%` }} /></div><div className="stat-foot">Based on entries <span>Target is 40%</span></div></article></div><div className="section-grid"><section className="panel spending-panel"><div className="panel-heading"><div><h2>Spending overview</h2><p>Where your money went this month</p></div><button className="select-button">This month⌄</button></div><div className="chart-area"><div className="donut"><div className="donut-center"><strong>{currency(totals.spending)}</strong><small>total spent</small></div></div><div className="legend">{["Housing", "Food & groceries", "Subscriptions", "Other"].map((category, index) => { const amount = transactions.filter(t => t.type === "expense" && (index === 3 ? !["Housing", "Food & groceries", "Subscriptions"].includes(t.category) : t.category === category)).reduce((sum, t) => sum + t.amount, 0); return <Legend key={category} color={["#5874e8", "#e5ad54", "#8b78d5", "#b9c5f4"][index]} label={category} amount={currency(amount)} percent={totals.spending ? `${((amount / totals.spending) * 100).toFixed(1)}%` : "0%"} />; })}</div></div></section><section className="panel upcoming-panel"><div className="panel-heading"><div><h2>Upcoming</h2><p>Payments due soon</p></div><button className="text-button">View all →</button></div><Upcoming icon="▤" title="Education loan" meta="Due in 11 days · Sep 11" amount="$223.67" color="blue" /><Upcoming icon="⌂" title="Rent" meta="Due in 15 days · Sep 15" amount="$1,450.00" color="purple" /><Upcoming icon="◌" title="Car insurance" meta="Due in 22 days · Sep 22" amount="$118.40" color="gold" /></section></div><Transactions transactions={transactions.slice(0, 5)} compact onViewAll={onViewTransactions} /></>;
}

