import { FormEvent, useState } from "react";
import { ApiRecurringBill } from "../../services/api";
import { CalendarInput } from "./CalendarInput";
import { currency } from "./format";

export function RecurringBills({ bills, onSubmit, onRemove, onUpdate }: { bills: ApiRecurringBill[]; onSubmit: (event: FormEvent<HTMLFormElement>) => void | Promise<void>; onRemove: (id: string) => void | Promise<void>; onUpdate: (id: string, event: FormEvent<HTMLFormElement>) => void | Promise<void> }) {
  const [editingId, setEditingId] = useState<number | null>(null);
  const edit = bills.find(bill => bill.id === editingId);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!edit) return; await onUpdate(String(edit.id), event); setEditingId(null); };
  return <div className="feature-grid"><section className="panel"><div className="panel-heading"><div><h2>Recurring bills</h2><p>Upcoming payments you want to remember</p></div></div>{bills.length ? bills.map(bill => editingId === bill.id ? <form className="inline-form feature-form" key={bill.id} onSubmit={save}><label>Name<input name="name" defaultValue={bill.name} required /></label><label>Amount<input name="amount" type="number" min="0.01" step="0.01" defaultValue={bill.amount} required /></label><label>Category<select name="category" defaultValue={bill.category}><option>Housing</option><option>Insurance</option><option>Subscriptions</option><option>Utilities</option><option>Other</option></select></label><label>Frequency<select name="frequency" defaultValue={bill.frequency}><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label><label>Next due date<CalendarInput name="next_due" defaultValue={bill.next_due} required /></label><button className="primary-button full" type="submit">Save changes</button></form> : <div className="account-row" key={bill.id}><div className="account-icon">↻</div><div><strong>{bill.name}</strong><small>{bill.category} · {bill.frequency} · due {bill.next_due}</small></div><b>{currency(bill.amount)}</b><button type="button" className="edit-link" onClick={() => setEditingId(bill.id)} aria-label={`Edit ${bill.name}`}>✎</button><button type="button" className="delete-link" onClick={() => { void onRemove(String(bill.id)); }} aria-label={`Remove ${bill.name}`}>×</button></div>) : <div className="empty-state">No recurring bills yet. Add your first one.</div>}</section><form className="panel inline-form" onSubmit={onSubmit}><h2>Add a recurring bill</h2><p>Track rent, insurance, subscriptions, and other scheduled costs.</p><label>Name<input name="name" placeholder="e.g. Rent" required /></label><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required /></label><label>Category<select name="category" defaultValue="Other"><option>Housing</option><option>Insurance</option><option>Subscriptions</option><option>Utilities</option><option>Other</option></select></label><label>Frequency<select name="frequency" defaultValue="monthly"><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label><label>Next due date<CalendarInput name="next_due" required /></label><button className="primary-button full" type="submit">Save recurring bill</button></form></div>;
}
