import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { financeApi, ApiAccount, ApiBudget, ApiGoal, ApiLoan, ApiLoanPayment, ApiRecurringBill, ApiTransaction } from "../services/api";
import { Account, Transaction } from "../components/moneyflow/types";
import { localDateString } from "../services/localDate";

function mapRecords(accounts: ApiAccount[], transactions: ApiTransaction[]) {
  const names = new Map(accounts.map(account => [account.id, account.name]));
  const uiTransactions: Transaction[] = transactions.map(transaction => ({ id: String(transaction.id), name: transaction.name, category: transaction.category, date: transaction.occurred_on, amount: Number(transaction.amount), type: transaction.transaction_type, account: names.get(transaction.account_id) || "Unknown account", notes: transaction.notes }));
  const balances = new Map<number, number>(accounts.map(account => [account.id, Number(account.opening_balance)]));
  transactions.forEach(transaction => balances.set(transaction.account_id, (balances.get(transaction.account_id) || 0) + (transaction.transaction_type === "income" ? Number(transaction.amount) : -Number(transaction.amount))));
  const uiAccounts: Account[] = accounts.filter(account => !account.is_archived).map(account => ({ id: String(account.id), name: account.name, type: account.account_type, balance: balances.get(account.id) || 0, currency: account.currency }));
  return { accounts: uiAccounts, transactions: uiTransactions };
}

export function useBackendFinance(enabled: boolean) {
  const [accounts, setAccounts] = useState<Account[]>([]); const [transactions, setTransactions] = useState<Transaction[]>([]); const [budgets, setBudgets] = useState<ApiBudget[]>([]); const [loans, setLoans] = useState<ApiLoan[]>([]); const [goals, setGoals] = useState<ApiGoal[]>([]); const [loanPayments, setLoanPayments] = useState<Record<number, ApiLoanPayment[]>>({}); const [recurringBills, setRecurringBills] = useState<ApiRecurringBill[]>([]); const [loading, setLoading] = useState(enabled); const [error, setError] = useState("");
  const refresh = useCallback(async () => { if (!enabled) return; setLoading(true); setError(""); try { const [apiAccounts, apiTransactions, apiBudgets, apiLoans, apiGoals, apiBills] = await Promise.all([financeApi.accounts(), financeApi.transactions(), financeApi.budgets(), financeApi.loans(), financeApi.goals(), financeApi.recurringBills()]); const mapped = mapRecords(apiAccounts, apiTransactions); const paymentResults = await Promise.all(apiLoans.map(loan => financeApi.loanPayments(String(loan.id)))); const payments = Object.fromEntries(apiLoans.map((loan, index) => [loan.id, paymentResults[index]])); setAccounts(mapped.accounts); setTransactions(mapped.transactions); setBudgets(apiBudgets); setLoans(apiLoans); setGoals(apiGoals); setLoanPayments(payments); setRecurringBills(apiBills); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load your finances."); } finally { setLoading(false); } }, [enabled]);
  useEffect(() => { void refresh(); }, [refresh]);
  const addTransaction = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const account = accounts.find(item => item.name === String(data.get("account"))); if (!account) throw new Error("Choose an account first."); await financeApi.createTransaction({ account_id: Number(account.id), transaction_type: data.get("type") as "expense" | "income", amount: Number(data.get("amount")), name: String(data.get("name")), category: String(data.get("category")), notes: String(data.get("notes") || ""), occurred_on: String(data.get("occurred_on") || localDateString()) }); await refresh(); };
  const addAccount = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); await financeApi.createAccount({ name: String(data.get("name")), account_type: String(data.get("type")).toLowerCase(), currency: "USD", opening_balance: Number(data.get("balance")) }); await refresh(); event.currentTarget.reset(); };
  const removeAccount = async (id: string) => { await financeApi.deleteAccount(id); await refresh(); };
  const removeTransaction = async (id: string) => { await financeApi.deleteTransaction(id); await refresh(); };
  const editTransaction = async (id: string, event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const account = accounts.find(item => item.name === String(data.get("account"))); if (!account) throw new Error("Choose an account first."); await financeApi.updateTransaction(id, { account_id: Number(account.id), transaction_type: data.get("type") as "expense" | "income", amount: Number(data.get("amount")), name: String(data.get("name")), category: String(data.get("category")), notes: String(data.get("notes") || ""), occurred_on: String(data.get("occurred_on") || localDateString()) }); await refresh(); };
  const addBudget = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); await financeApi.createBudget({ category: String(data.get("category")), monthly_limit: Number(data.get("monthly_limit")) }); await refresh(); event.currentTarget.reset(); };
  const addLoan = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); await financeApi.createLoan({ name: String(data.get("name")), remaining_balance: Number(data.get("remaining_balance")), minimum_payment: Number(data.get("minimum_payment") || 0), interest_rate: Number(data.get("interest_rate") || 0), due_date: String(data.get("due_date") || "") || undefined }); await refresh(); event.currentTarget.reset(); };
  const addGoal = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); await financeApi.createGoal({ name: String(data.get("name")), target_amount: Number(data.get("target_amount")), current_amount: Number(data.get("current_amount") || 0), target_date: String(data.get("target_date") || "") || undefined }); await refresh(); event.currentTarget.reset(); };
  const removeBudget = async (id: string) => { await financeApi.deleteBudget(id); await refresh(); };
  const updateBudget = async (id: string, event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); await financeApi.updateBudget(id, { category: String(data.get("category")), monthly_limit: Number(data.get("monthly_limit")) }); await refresh(); };
  const removeLoan = async (id: string) => { await financeApi.deleteLoan(id); await refresh(); };
  const updateLoan = async (id: string, event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); await financeApi.updateLoan(id, { name: String(data.get("name")), remaining_balance: Number(data.get("remaining_balance")), minimum_payment: Number(data.get("minimum_payment") || 0), interest_rate: Number(data.get("interest_rate") || 0), due_date: String(data.get("due_date") || "") || undefined }); await refresh(); };
  const removeGoal = async (id: string) => { await financeApi.deleteGoal(id); await refresh(); };
  const updateGoal = async (id: string, event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); await financeApi.updateGoal(id, { name: String(data.get("name")), target_amount: Number(data.get("target_amount")), current_amount: Number(data.get("current_amount") || 0), target_date: String(data.get("target_date") || "") || undefined }); await refresh(); };
  const addLoanPayment = async (loanId: string, event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); await financeApi.createLoanPayment(loanId, { amount: Number(data.get("amount")), principal_amount: Number(data.get("principal_amount")), interest_amount: Number(data.get("interest_amount") || 0), paid_on: String(data.get("paid_on") || localDateString()), note: String(data.get("note") || "") || undefined }); await refresh(); event.currentTarget.reset(); };
  const removeLoanPayment = async (loanId: string, paymentId: string) => { await financeApi.deleteLoanPayment(loanId, paymentId); await refresh(); };
  const addRecurringBill = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); await financeApi.createRecurringBill({ name: String(data.get("name")), amount: Number(data.get("amount")), category: String(data.get("category")), frequency: data.get("frequency") as "weekly" | "monthly" | "yearly", next_due: String(data.get("next_due")) }); await refresh(); event.currentTarget.reset(); };
  const removeRecurringBill = async (id: string) => { await financeApi.deleteRecurringBill(id); await refresh(); };
  const updateRecurringBill = async (id: string, event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); await financeApi.updateRecurringBill(id, { name: String(data.get("name")), amount: Number(data.get("amount")), category: String(data.get("category")), frequency: data.get("frequency") as "weekly" | "monthly" | "yearly", next_due: String(data.get("next_due")) }); await refresh(); };
  const payRecurringBill = async (id: string, event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); await financeApi.payRecurringBill(id, Number(data.get("account_id")), String(data.get("occurred_on"))); await refresh(); };
  const payRecurringBillNow = async (id: string, accountId: number, occurredOn: string) => { await financeApi.payRecurringBill(id, accountId, occurredOn); await refresh(); };
  const income = transactions.filter(transaction => transaction.type === "income").reduce((sum, transaction) => sum + transaction.amount, 0); const spending = transactions.filter(transaction => transaction.type === "expense").reduce((sum, transaction) => sum + transaction.amount, 0);
  return { accounts, transactions, budgets, loans, goals, loanPayments, recurringBills, balance: useMemo(() => accounts.reduce((sum, account) => sum + account.balance, 0), [accounts]), totals: { income, spending }, loading, error, addTransaction, addAccount, removeAccount, removeTransaction, editTransaction, addBudget, updateBudget, addLoan, updateLoan, addGoal, updateGoal, removeBudget, removeLoan, removeGoal, addLoanPayment, removeLoanPayment, addRecurringBill, updateRecurringBill, payRecurringBill, payRecurringBillNow, removeRecurringBill };
}
